#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STANDARD REMOVE
#=================================================
# REMOVE SERVICE INTEGRATION IN YUNOHOST
#=================================================

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status tor >/dev/null
then
	ynh_script_progression "Removing Tor service integration..."
	yunohost service remove tor
fi

#=================================================
# STOP AND REMOVE SERVICE
#=================================================
ynh_script_progression "Stopping and removing the systemd service..."

# Remove the dedicated systemd config
ynh_config_remove_systemdtor

#=================================================
# SPECIFIC REMOVE
#=================================================
# REMOVE VARIOUS FILES
#=================================================
ynh_script_progression "Removing various files..."

# Remove a cron file
ynh_safe_rm "/etc/tor/torrc"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
