#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# REMOVE SERVICE INTEGRATION IN YUNOHOST
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

if ynh_hide_warnings yunohost service status tor >/dev/null; then
    yunohost service stop tor
    yunohost service remove tor
fi

if ynh_hide_warnings systemctl list-unit-files --all | grep -q "tor@default.service" >/dev/null; then
    systemctl stop tor@default
fi

ynh_safe_rm "/etc/tor/torrc"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
